title: Marie Curie Olympiad in Informatics
description: 
author: MCOI
github: //github.com/vnmcoi
about: 
# disqus_shortname: vnspoj
google_analytics: UA-162061519-1
avatar_url: /static/img/favicon.png
email: tutorialspoj@gmail.com

username: vnmcoi
repo: vnmcoi.github.io

social:
  # - icon: fa-facebook
  # link: "//facebook.com/huynhsamha"
  # - icon: fa-stack-overflow
  #   link: "//stackoverflow.com/users/8828489/huynhsamha"
  # - icon: fa-github
  #   link: "//github.com/vnmcoi"
  # - icon: fa-linkedin
  #   link: "//www.linkedin.com/in/huynhsamha"
  # - icon: fa-twitter
  #   link: "//twitter.com/huynhsamha"

share:
  # twitter_username: huynhsamha
  # fb_appid: 1749788565247320

urls:
  - text: Categories
    url: /category
  - text: Search
    url: /search
  - text: Wiki
    url: /wiki
  # - text: CodeLearn.io
  #   url: /code-learn
  # - text: Interview Questions
  #   url: /top-interview-questions
  - text: About Us
    url: /about
  - text: XML Feed
    url: /feed.xml
  # - text: XML Sitemap
  #   url: /sitemap.xml
  # - text: Join with us
  #   url: //github.com/vnmcoi

url: "//vnmcoi.github.io"
baseurl: ""
permalink: /problems/:title:output_ext
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
mathjax: true
gems:
  - jekyll-paginate
  - jekyll-gist

collections:
  category:
    output: true
  wiki:
    output: true
  wikivn:
    output: true

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

sass:
  style: compressed
